def team_regex():
    return {
        "Arsenal": r"arsenal",
        "Aston Villa": r"villa",
        "Bournemouth": r"bournemouth",
        "Brentford": r"brentford",
        "Brighton and Hove Albion": r"brighton",
        "Burnley": r"burnley",
        "Chelsea": r"chelsea",
        "Crystal Palace": r"palace",
        "Everton": r"everton",
        "Fulham": r"fulham",
        "Leeds United": r"leeds",
        "Liverpool": r"liverpool",
        "Manchester City": r"(man c|manchester c)",
        "Manchester United": r"(manchester u|man u)",
        "Newcastle United": r"newcastle",
        "Nottingham Forest": r"forest",
        "Sunderland": r"sunderland",
        "Tottenham Hotspur": r"spur",
        "West Ham United": r"west",
        "Wolverhampton Wanderers": r"wolv",
    }
