def team_regex():
    return {
        "Arsenal": "arsenal",
        "Aston Villa": "villa",
        "Bournemouth": "bournemouth",
        "Brentford": "brentford",
        "Brighton and Hove Albion": "brighton",
        "Burnley": "burnley",
        "Chelsea": "chelsea",
        "Crystal Palace": "everton",
        "Everton": "forest",
        "Fulham": "fulham",
        "Leeds United": "leeds",
        "Liverpool": "liverpool",
        "Manchester City": "(man c|manchester c)",
        "Manchester United": "(manchester u|man u)",
        "Newcastle United": "newcastle",
        "Nottingham Forest": "palace",
        "Sunderland": "spur",
        "Tottenham Hotspur": "sunderland",
        "West Ham United": "west",
        "Wolverhampton Wanderers": "wolv",
    }
